=== dpa1974/LND2017/ENTREGA 2 TRIMESTRE/metereologia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="metereologia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mediciones">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="medicion" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="temperatura">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:float" name="t_max"/>
                          <xs:element type="xs:float" name="t_min"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="viento">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="direccion">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="hora" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:float" name="velocidad_med"/>
                          <xs:element type="xs:float" name="racha_max"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:float" name="humedad"/>
                    <xs:element type="xs:string" name="presion_atm"/>
                    <xs:element name="mareas">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:time" name="plenamar" maxOccurs="unbounded" minOccurs="0"/>
                          <xs:element type="xs:time" name="bajamar" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="sol">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:time" name="amanecer"/>
                          <xs:element type="xs:time" name="atardecer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="presipitaciones"/>
                  </xs:sequence>
                  <xs:attribute type="xs:date" name="fecha" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="mes"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dpa1974/LND2017/ENTREGA 2 TRIMESTRE/metereologia.XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metereologia xsi:noNamespaceSchemaLocation ="metereologia.xsd"
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance">
<mediciones mes="Febrero">
<medicion fecha="2018-02-01">
 <temperatura>
     <t_max>16</t_max>
     <t_min>14</t_min>
 </temperatura>
 <viento>
     <direccion hora="06:00:00">NE</direccion>
     <velocidad_med>14.8</velocidad_med>
     <racha_max>22</racha_max>
     </viento> 
 <humedad>93</humedad>
 <presion_atm>1024hPa</presion_atm>
 <mareas>
     <plenamar>01:48:00</plenamar>
     <plenamar>14:14:00</plenamar>
     <bajamar>08:00:00</bajamar>
     <bajamar>20:11:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:43:00</amanecer>
     <atardecer>18:35:00</atardecer>
 </sol>
 <presipitaciones>0.12cm</presipitaciones>
</medicion>
<medicion fecha="2018-02-03">
 <temperatura>
     <t_max>17</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00">NE</direccion>
     <velocidad_med>28.8</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>92</humedad>
 <presion_atm>1024hPa</presion_atm>
 <mareas>
     <plenamar>02:33:00</plenamar>
     <plenamar>14:59:00</plenamar>
     <bajamar>08:45:00</bajamar>
     <bajamar>20:54:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:42:00</amanecer>
     <atardecer>18:36:00</atardecer>
 </sol>
 <presipitaciones>0.05cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-03">
 <temperatura>
     <t_max>19</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00">SO</direccion>
     <velocidad_med>38.8</velocidad_med>
     <racha_max>52</racha_max>
     </viento> 
 <humedad>77</humedad>
 <presion_atm>1014hPa</presion_atm>
 <mareas>
     <plenamar>03:18:00</plenamar>
     <plenamar>15:43:00</plenamar>
     <bajamar>09:29:00</bajamar>
     <bajamar>21:36:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:42:00</amanecer>
     <atardecer>18:37:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-04">
 <temperatura>
     <t_max>19</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00">SO</direccion>
     <velocidad_med>27.5</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>79</humedad>
 <presion_atm>1023hPa</presion_atm>
 <mareas>
     <plenamar>04:02:00</plenamar>
     <plenamar>16:26:00</plenamar>
     <bajamar>10:12:00</bajamar>
     <bajamar>22:19:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:41:00</amanecer>
     <atardecer>18:38:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-05">
 <temperatura>
     <t_max>19</t_max>
     <t_min>15.7</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00">NE</direccion>
     <velocidad_med>27.5</velocidad_med>
     <racha_max>35</racha_max>
     </viento> 
 <humedad>83</humedad>
 <presion_atm>1021hPa</presion_atm>
 <mareas>
     <plenamar>04:47:00</plenamar>
     <plenamar>17:11:00</plenamar>
     <bajamar>10:56:00</bajamar>
     <bajamar>23:04:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:40:00</amanecer>
     <atardecer>18:38:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-06">
 <temperatura>
     <t_max>18.6</t_max>
     <t_min>14.3</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00">N</direccion>
     <velocidad_med>25.7</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>79</humedad>
 <presion_atm>1022hPa</presion_atm>
 <mareas>
     <plenamar>05:34:00</plenamar>
     <plenamar>18:00:00</plenamar>
     <bajamar>11:43:00</bajamar>
     <bajamar>23:55:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:40:00</amanecer>
     <atardecer>18:39:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-07">
 <temperatura>
     <t_max>18.8</t_max>
     <t_min>12.7</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">SO</direccion>
     <velocidad_med>27.5</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>77</humedad>
 <presion_atm>1022hPa</presion_atm>
 <mareas>
     <plenamar>06:28:00</plenamar>
     <plenamar>18:59:00</plenamar>
     <bajamar>12:40:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:39:00</amanecer>
     <atardecer>18:40:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-08">
 <temperatura>
     <t_max>15</t_max>
     <t_min>14.1</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">NE</direccion>
     <velocidad_med>42.6</velocidad_med>
     <racha_max>57</racha_max>
     </viento> 
 <humedad>73</humedad>
 <presion_atm>1026hPa</presion_atm>
 <mareas>
     <plenamar>07:34:00</plenamar>
     <plenamar>20:14:00</plenamar>
     <bajamar>01:02:00</bajamar>
     <bajamar>13:51:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:38:00</amanecer>
     <atardecer>18:41:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-09">
 <temperatura>
     <t_max>18.5</t_max>
     <t_min>14.1</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">NNE</direccion>
     <velocidad_med>42.5</velocidad_med>
     <racha_max>52</racha_max>
     </viento> 
 <humedad>82</humedad>
 <presion_atm>1026hPa</presion_atm>
 <mareas>
     <plenamar>08:53:00</plenamar>
     <plenamar>21:32:00</plenamar>
     <bajamar>02:28:00</bajamar>
     <bajamar>15:09:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:38:00</amanecer>
     <atardecer>18:42:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-10">
 <temperatura>
     <t_max>21</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">SO</direccion>
     <velocidad_med>37.5</velocidad_med>
     <racha_max>55</racha_max>
     </viento> 
 <humedad>82.5</humedad>
 <presion_atm>1025hPa</presion_atm>
 <mareas>
     <plenamar>10:08:00</plenamar>
     <plenamar>22:37:00</plenamar>
     <bajamar>03:52:00</bajamar>
     <bajamar>16:16:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:37:00</amanecer>
     <atardecer>18:42:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-11">
 <temperatura>
     <t_max>19</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">SO</direccion>
     <velocidad_med>40.7</velocidad_med>
     <racha_max>54</racha_max>
     </viento> 
 <humedad>72.4</humedad>
 <presion_atm>1025hPa</presion_atm>
 <mareas>
     <plenamar>11:06:00</plenamar>
     <plenamar>23:26:00</plenamar>
     <bajamar>04:56:00</bajamar>
     <bajamar>17:08:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:36:00</amanecer>
     <atardecer>18:43:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-12">
 <temperatura>
     <t_max>18.6</t_max>
     <t_min>15.3</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">NE</direccion>
     <velocidad_med>25.9</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>82.4</humedad>
 <presion_atm>1025hPa</presion_atm>
 <mareas>
     <plenamar>11:50:00</plenamar>
     <bajamar>05:42:00</bajamar>
     <bajamar>17:50:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:35:00</amanecer>
     <atardecer>18:44:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-13">
 <temperatura>
     <t_max>19.2</t_max>
     <t_min>13.7</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">SO</direccion>
     <velocidad_med>13</velocidad_med>
     <racha_max>32</racha_max>
     </viento> 
 <humedad>89</humedad>
 <presion_atm>1024hPa</presion_atm>
 <mareas>
     <plenamar>00:06:00</plenamar>
     <plenamar>12:28:00</plenamar>
     <bajamar>06:20:00</bajamar>
     <bajamar>18:26:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:35:00</amanecer>
     <atardecer>18:45:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-14">
 <temperatura>
     <t_max>18.5</t_max>
     <t_min>13.8</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">NE</direccion>
     <velocidad_med>24.1</velocidad_med>
     <racha_max>33</racha_max>
     </viento> 
 <humedad>90</humedad>
 <presion_atm>1025hPa</presion_atm>
 <mareas>
     <plenamar>00:42:00</plenamar>
     <plenamar>13:01:00</plenamar>
     <bajamar>06:53:00</bajamar>
     <bajamar>18:59:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:34:00</amanecer>
     <atardecer>18:45:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-15">
 <temperatura>
     <t_max>19</t_max>
     <t_min>15</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">SO</direccion>
     <velocidad_med>22.2</velocidad_med>
     <racha_max>31</racha_max>
     </viento> 
 <humedad>94</humedad>
 <presion_atm>1024hPa</presion_atm>
 <mareas>
     <plenamar>01:15:00</plenamar>
     <plenamar>13:34:00</plenamar>
     <bajamar>07:25:00</bajamar>
     <bajamar>19:31:00</bajamar>
 </mareas>
 <sol>
     <amanecer>07:33:00</amanecer>
     <atardecer>18:46:00</atardecer>
 </sol>
 <presipitaciones>0cm</presipitaciones>  
</medicion>
<medicion fecha="2018-02-16">
 <temperatura>
     <t_max>21</t_max>
     <t_min>16</t_min>
 </temperatura>
 <viento>
     <direccion hora="6:00:00">NNE</direccion>
     <velocidad_med>24.1</velocidad_med>
     <racha_max>28</racha_max>
     </viento> 
 <humedad>88</humedad>
 <presion_atm>1024hPa</presion_atm>
 <mareas>
